name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: "weather message"
        required: false

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: GET UP
        env:
            GITHUB_TOKEN: ${{ secrets.YAN_GITHUB_ACCESS_TOKEN }}
            WEATHER_MESSAGE: ${{ github.event.inputs.message }}
        run: |
          echo "Repository: ${{ github.repository }}"
          python get_up.py ${{ secrets.YAN_GITHUB_ACCESS_TOKEN }} ${{ github.repository }} ${{ env.WEATHER_MESSAGE }}
